--------------------------------------------------------
--  File created - Tuesday-August-02-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Procedure INSERTUSINGPORTAL
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SYSTEM"."INSERTUSINGPORTAL" (
    PGENREID IN INT,
    PTITLE IN NVARCHAR2,
    PDESCRIPTION IN NVARCHAR2,
    PLANGUAGE IN NVARCHAR2,
    PRELEASE_DATE IN DATE,
    PDIRECTOR IN NVARCHAR2,
    PACTORF IN NVARCHAR2,
    PACTORL IN NVARCHAR2,
    PNATIONALITY IN NVARCHAR2,
    PDOB IN DATE,
    PSTARS IN INT,
    PMOVIEID  IN INT,
    PACTORID IN INT,
    PRATINGID IN INT
)
AS
BEGIN       

  INSERT INTO MOVIES(MOVIEID, TITLE, DESCRIPTION, LANGUAGE, RELEASE_DATE, DIRECTOR) 
  VALUES (PMOVIEID, PTITLE, PDESCRIPTION, PLANGUAGE, PRELEASE_DATE, PDIRECTOR);

  INSERT INTO RATING(RATINGID, MOVIEID, STARS)
  VALUES(PRATINGID, PMOVIEID, PSTARS);

  INSERT INTO MOVIEGENRES(MOVIEID, GENREID)
  VALUES(PMOVIEID, PGENREID);

  INSERT INTO ACTORS(ACTORID, FIRSTNAME, LASTNAME, NATIONALITY, DOB)
  VALUES(PACTORID, PACTORF, PACTORL, PNATIONALITY, PDOB);

  INSERT INTO MOVIEACTOR(MOVIEID, ACTORID)
  VALUES(PMOVIEID, PACTORID);

END InsertUsingPortal;

/
