--------------------------------------------------------
--  Ref Constraints for Table MOVIEACTOR
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MOVIEACTOR" ADD CONSTRAINT "MOVIEACTOR_FK1" FOREIGN KEY ("MOVIEID")
	  REFERENCES "SYSTEM"."MOVIES" ("MOVIEID") ENABLE;
  ALTER TABLE "SYSTEM"."MOVIEACTOR" ADD CONSTRAINT "MOVIEACTOR_FK2" FOREIGN KEY ("ACTORID")
	  REFERENCES "SYSTEM"."ACTORS" ("ACTORID") ENABLE;
  
--------------------------------------------------------
--  Ref Constraints for Table MOVIEGENRES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MOVIEGENRES" ADD CONSTRAINT "MOVIEGENRES_FK2" FOREIGN KEY ("MOVIEID")
	  REFERENCES "SYSTEM"."MOVIES" ("MOVIEID") ENABLE;
  ALTER TABLE "SYSTEM"."MOVIEGENRES" ADD CONSTRAINT "MOVIEGENRES_FK1" FOREIGN KEY ("GENREID")
	  REFERENCES "SYSTEM"."GENRES" ("GENREID") ENABLE;

--------------------------------------------------------
--  Constraints for Table USER_TABLE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."USER_TABLE" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."USER_TABLE" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."USER_TABLE" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."USER_TABLE" ADD CONSTRAINT "USER_TABLE_PK" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  
--------------------------------------------------------
--  Constraints for Table RATING
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."RATING" MODIFY ("RATINGID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."RATING" MODIFY ("STARS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."RATING" ADD CONSTRAINT "RATING_PK" PRIMARY KEY ("RATINGID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."RATING" ADD CONSTRAINT "CHECK_RATING" CHECK (STARS > 1) ENABLE;
  
--------------------------------------------------------
--  Constraints for Table MOVIES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MOVIES" MODIFY ("MOVIEID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MOVIES" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MOVIES" MODIFY ("LANGUAGE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MOVIES" MODIFY ("RELEASE_DATE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MOVIES" MODIFY ("DIRECTOR" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MOVIES" ADD CONSTRAINT "MOVIES_PK" PRIMARY KEY ("MOVIEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  
--------------------------------------------------------
--  Constraints for Table ACTORS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ACTORS" MODIFY ("ACTORID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ACTORS" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ACTORS" MODIFY ("LASTNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ACTORS" MODIFY ("NATIONALITY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ACTORS" ADD CONSTRAINT "ACTORS_PK" PRIMARY KEY ("ACTORID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."ACTORS" ADD CONSTRAINT "CHECK_NATIONALITY" CHECK (NATIONALITY IN ('American', 'Indian')) ENABLE;

--------------------------------------------------------
--  Constraints for Table GENRES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GENRES" MODIFY ("GENREID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GENRES" MODIFY ("GENRENAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GENRES" ADD CONSTRAINT "GENRES_PK" PRIMARY KEY ("GENREID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."GENRES" ADD CONSTRAINT "CHECK_GENRE_NAME" CHECK (GENRENAME IN ('Action', 'Horror', 'Crime')) ENABLE;
  
  
